name: Validate HTML and CSS
on:
  push:
jobs:
  validate:
    name: Validate HTML and CSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use NodeJS 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install and Build
        run:  |
          npm install
          npm run build
      - name: Run HTML Check 📑
        uses: Cyb3r-Jak3/html5validator-action@master
        with:
          root: dist/
          format: text
      - name: Run CSS Check 🎨
        uses: Cyb3r-Jak3/html5validator-action@master
        with:
          root: dist/
          blacklist: index.html
          format: text
          css: true
